version: '3'
services:
  router:
    build: .
    image: helium/router:latest
    container_name: helium_router
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - "/var/data:/var/data"
    depends_on:
      - prometheus
  prometheus:
      image: prom/prometheus
      container_name: helium_prometheus
      volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml