version: '3'
services:
  router:
    build: .
    image: helium/router:latest
    container_name: helium_router
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - "/var/data:/var/data"